export const SUPPORTED_NODE_TYPES = new Set([
  "FRAME", "GROUP", "RECTANGLE", "ELLIPSE", "LINE", "TEXT", "VECTOR", "SVG",
  "COMPONENT", "COMPONENT_SET", "INSTANCE", "BOOLEAN_OPERATION", "POLYGON", "STAR", "SECTION", "SLICE", "ARC"
]);

export const SUPPORTED_PAINT_TYPES = new Set([
  "SOLID", "GRADIENT_LINEAR", "GRADIENT_RADIAL", "GRADIENT_ANGULAR", "GRADIENT_DIAMOND", "IMAGE"
]);
